function [parameters] = parameter_setup

prompt={'Experiment name'...
    'Correction of channel offset (no=0,auto=1,fixed=2)'...
    'mask criterion: AND (0) / OR (1) / REDonly (2) '...
    'initial threshold'...
    'single size threshold? (0/1)'...
    'threshold based on perimeter/area ratio? (0/1)'...
    'lower threshold bac size'...
    'upper threshold bac size'...
    'path to results dir'...
    'Display detected bacs (0/1)'...
    'Number of colour channels (2/3)'...
    };

defans = {'3c test',...
    '0'...
    '2'...
    '2'...
    '1'...
    '0'...
    '250'...
    '3500'...
    '/Users/kristina/Desktop/analysis FT'...
    '1'...
    '2'...
    };

info = inputdlg(prompt,'Input Parameters',1,defans);

parameters.exp_name = info{1};
parameters.offsetcorr = str2double(info{2});
parameters.or = str2double(info{3});
parameters.binary_thres = str2double(info{4});
parameters.sizethresboolean = str2double(info{5});
parameters.perithresboolean = str2double(info{6});
parameters.sizethres = str2double(info{7});
parameters.sizethres_upperlimit = str2double(info{8});
parameters.loc4dir = info{9};
parameters.display_images = str2double(info{10});
parameters.nocolours = str2double(info{11});

objectives = {'20x NA0.5', '20x NA0.75','40x NA0.95', '60x NA0.95','60x NA1.4','60x NA1.49'};
[parameters.objective,~] = listdlg('PromptString','Select an objective:',...
                'SelectionMode','single',...
                'ListString',objectives);


end





